### ISSUE TITLE
Navigation Drawer doesnot toggle leftView Sometimes but only dim the view

### ISSUE THREAD

**Issue by sarojraut** [CosmicMind/Material#1003]
I found that the issue occur due to toggle of view through button and dragging action at the same time.

**Comment by chaitanya-ramji** [comment]
@sarojraut can you describe the steps to reproduce the issue?

**Comment by danieldahan** [comment]
@sarojraut what version of Material are you using? There was an issue before that is similar to this and it was fixed. Thank you!

**Comment by sarojraut** [comment]
Sorry, it is not solved the issue still exist in the latest version.

**Comment by danieldahan** [comment]
@sarojraut well I am not going to confirm it is an issue until I see your code setup and what is happening there. Please share a reproducible project that I can investigate. Thank you!
