### ISSUE TITLE
Navigation Item Title Label Alignment

### ISSUE THREAD

**Issue by zgosalvez** [CosmicMind/Material#227]
When setting `navigationItem` elements, the `titleLabel`'s alignment does not work properly if the controls are not set. E.g.

```swift
// titleLabel.textAlignment = .Left
// ...
navigationItem.leftControls = [menuButton]
navigationItem.titleLabel = titleLabel
navigationItem.rightControls = [] // without this the titleLabel will overlap the leftControls.
```

**Comment by danieldahan** [comment]
Yes I found this bug last night. It is fixed for the release later today. :)

---------------------------------------
Daniel Dahan
 
M: +1 647.627.0770
Skype: djondahan

**Comment by danieldahan** [comment]
Will be in release 1.37.0, which I am testing and then releasing.

**Comment by zgosalvez** [comment]
This is still broken if I set `titleLabel.textAlignment = .Center`, with or without `navigationItem.rightControls = []`

**Comment by danieldahan** [comment]
It's not broken. The titleLabel is affected by the controls, so it only aligns when in equal space. If you want an always centre alignment, use the title property. 

```swift
navigationItem.title = "My Title"
```
